from typing import List, Dict, Any


def build_markdown_report(
    review_id: int,
    filename: str,
    language: str,
    risk_level: str,
    score: int,
    findings: List[Dict[str, Any]],
    summary: str
) -> str:
    report = f"""# DevGuard AI Security Review Report

## File

- Review ID: {review_id}
- Filename: `{filename}`
- Language: `{language}`
- Risk Level: **{risk_level}**
- Score: **{score}/100**

## Summary

{summary}

## Findings

"""

    if not findings:
        report += "No findings were detected by the current MVP rule set.\n"
        return report

    for index, finding in enumerate(findings, start=1):
        report += f"""### {index}. {finding["title"]}

- Severity: **{finding["severity"]}**
- Category: `{finding["category"]}`
- Line: `{finding.get("line", "N/A")}`

**Explanation:**  
{finding["explanation"]}

**Recommendation:**  
{finding["recommendation"]}

"""

    report += """
## Note

This report was generated by a rule-based MVP scanner. It is designed for educational and developer-assistance purposes and should not be treated as a complete professional security audit.
"""

    return report
